import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, Alert, Platform, ActivityIndicator, ScrollView, Image } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { colors, spacing, borderRadius, shadow } from '../../theme/colors';
import apiClient from '../../services/api/apiClient';
import { resolveProductImageUrl } from '../../utils/imageUtils';

export default function SellerCreateShipmentScreen({ route, navigation }: any) {
    const { orderId } = route.params || {};
    const insets = useSafeAreaInsets();
    
    const [order, setOrder] = useState<any>(null);
    const [loading, setLoading] = useState(true);
    const [submitting, setSubmitting] = useState(false);

    useEffect(() => {
        const fetchOrder = async () => {
            try {
                const data = await apiClient.get(`/orders/${orderId}`);
                setOrder(data);
            } catch (error) {
                console.warn('Fetch order error:', error);
                if (Platform.OS === 'web') window.alert('Không thể tải thông tin đơn hàng.');
                else Alert.alert('Lỗi', 'Không thể tải thông tin đơn hàng.');
                navigation.goBack();
            } finally {
                setLoading(false);
            }
        };
        fetchOrder();
    }, [orderId]);

    const handleCreateShipment = async () => {
        setSubmitting(true);
        try {
            await apiClient.post(`/orders/${orderId}/shipment`, {
                shipmentMethod: 'Giao Hàng Nhanh',
                // trackingNumber will be auto-generated by the backend if null
            });
            
            if (Platform.OS === 'web') {
                window.alert('Tạo vận đơn thành công! Đơn hàng sẽ được chuyển sang tab Vận chuyển.');
            } else {
                Alert.alert('Thành công', 'Tạo vận đơn thành công! Đơn hàng sẽ được chuyển sang tab Vận chuyển.');
            }
            // Replace current screen to remove it from stack, leaving the previous SellerOrders underneath
            navigation.replace('SellerOrders', { activeTab: 'Vận chuyển' });
        } catch (error: any) {
            if (Platform.OS === 'web') window.alert(error.message || 'Lỗi tạo vận đơn');
            else Alert.alert('Lỗi', error.message || 'Lỗi tạo vận đơn');
        } finally {
            setSubmitting(false);
        }
    };

    if (loading) {
        return (
            <View style={[styles.container, { justifyContent: 'center', alignItems: 'center' }]}>
                <ActivityIndicator size="large" color={colors.primary} />
            </View>
        );
    }

    if (!order) return null;

    const address = order.shippingAddress;
    const items = order.items || order.orderItems || [];
    const firstItem = items[0];
    const productImage = firstItem?.productImage ? resolveProductImageUrl(firstItem.productImage) : null;

    return (
        <View style={[styles.container, { paddingTop: insets.top }]}>
            <View style={styles.header}>
                <TouchableOpacity style={styles.backBtn} onPress={() => navigation.goBack()}>
                    <Ionicons name="arrow-back" size={24} color={colors.text} />
                </TouchableOpacity>
                <Text style={styles.headerTitle}>Tạo Vận Đơn</Text>
                <View style={{ width: 40 }} />
            </View>

            <ScrollView contentContainerStyle={styles.content}>
                <View style={styles.card}>
                    <View style={styles.cardHeader}>
                        <Ionicons name="receipt-outline" size={20} color={colors.primary} />
                        <Text style={styles.cardTitle}>Thông tin đơn hàng</Text>
                    </View>
                    <View style={styles.infoRow}>
                        <Text style={styles.label}>Mã đơn:</Text>
                        <Text style={styles.value}>{order.orderNumber}</Text>
                    </View>
                    <View style={styles.infoRow}>
                        <Text style={styles.label}>Ngày đặt:</Text>
                        <Text style={styles.value}>{new Date(order.orderDate).toLocaleString('vi-VN')}</Text>
                    </View>
                    <View style={styles.infoRow}>
                        <Text style={styles.label}>Tổng thu:</Text>
                        <Text style={[styles.value, { color: colors.primary, fontWeight: '700' }]}>
                            {order.totalAmount?.toLocaleString('vi-VN')}đ
                        </Text>
                    </View>
                </View>

                <View style={styles.card}>
                    <View style={styles.cardHeader}>
                        <Ionicons name="location-outline" size={20} color={colors.secondary} />
                        <Text style={styles.cardTitle}>Địa chỉ lấy & giao hàng</Text>
                    </View>
                    <Text style={styles.addressName}>Người nhận ID: {order.buyerId}</Text>
                    <Text style={styles.addressText}>
                        {address?.streetAddress}, {address?.city}, {address?.state} {address?.zipcode}
                    </Text>
                </View>

                <View style={styles.card}>
                    <View style={styles.cardHeader}>
                        <Ionicons name="cube-outline" size={20} color={colors.success} />
                        <Text style={styles.cardTitle}>Sản phẩm ({items.length})</Text>
                    </View>
                    
                    <View style={styles.productRow}>
                        <View style={styles.productImgWrap}>
                            {productImage ? (
                                <Image source={{ uri: productImage }} style={styles.productImg} resizeMode="cover" />
                            ) : (
                                <Ionicons name="cube-outline" size={24} color={colors.textMuted} />
                            )}
                        </View>
                        <View style={styles.productInfo}>
                            <Text style={styles.productName} numberOfLines={2}>{firstItem?.productName || 'Sản phẩm'}</Text>
                            <Text style={styles.productPrice}>
                                {firstItem?.unitPrice?.toLocaleString('vi-VN')}đ x {firstItem?.quantity}
                            </Text>
                        </View>
                    </View>
                    {items.length > 1 && (
                        <Text style={styles.moreItemsText}>+ {items.length - 1} sản phẩm khác...</Text>
                    )}
                </View>

                <View style={styles.card}>
                    <View style={styles.cardHeader}>
                        <Ionicons name="car-outline" size={20} color={colors.warning} />
                        <Text style={styles.cardTitle}>Đơn vị vận chuyển</Text>
                    </View>
                    <View style={styles.shippingMethod}>
                        <Ionicons name="checkmark-circle" size={20} color={colors.primary} />
                        <Text style={styles.shippingMethodText}>Giao Hàng Nhanh (Mặc định)</Text>
                    </View>
                </View>
            </ScrollView>

            <View style={[styles.footer, { paddingBottom: insets.bottom > 0 ? insets.bottom : 16 }]}>
                <TouchableOpacity 
                    style={[styles.submitBtn, submitting && { opacity: 0.7 }]} 
                    onPress={handleCreateShipment}
                    disabled={submitting}
                >
                    {submitting ? (
                        <ActivityIndicator color="#FFF" />
                    ) : (
                        <>
                            <Ionicons name="print-outline" size={20} color="#FFF" />
                            <Text style={styles.submitBtnText}>In Vận Đơn & Xác Nhận</Text>
                        </>
                    )}
                </TouchableOpacity>
            </View>
        </View>
    );
}

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: spacing.md, paddingVertical: 12, backgroundColor: colors.white, ...shadow.sm, zIndex: 10 },
    backBtn: { padding: 8, marginLeft: -8 },
    headerTitle: { fontSize: 18, fontWeight: '700', color: colors.text },
    
    content: { padding: 16, paddingBottom: 40 },
    
    card: { backgroundColor: colors.white, borderRadius: borderRadius.md, padding: 16, marginBottom: 16, ...shadow.sm },
    cardHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12, gap: 8, borderBottomWidth: 1, borderBottomColor: colors.borderLight, paddingBottom: 8 },
    cardTitle: { fontSize: 15, fontWeight: '700', color: colors.text },
    
    infoRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
    label: { fontSize: 14, color: colors.textSecondary },
    value: { fontSize: 14, color: colors.text, fontWeight: '500' },
    
    addressName: { fontSize: 15, fontWeight: '600', color: colors.text, marginBottom: 4 },
    addressText: { fontSize: 14, color: colors.textSecondary, lineHeight: 20 },
    
    productRow: { flexDirection: 'row', alignItems: 'center' },
    productImgWrap: { width: 60, height: 60, borderRadius: 8, backgroundColor: colors.background, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
    productImg: { width: '100%', height: '100%', borderRadius: 8 },
    productInfo: { flex: 1 },
    productName: { fontSize: 14, fontWeight: '600', color: colors.text, marginBottom: 4 },
    productPrice: { fontSize: 14, color: colors.textSecondary },
    moreItemsText: { fontSize: 13, color: colors.primary, marginTop: 8, fontStyle: 'italic' },
    
    shippingMethod: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.primary + '10', padding: 12, borderRadius: 8, gap: 8, borderWidth: 1, borderColor: colors.primary + '30' },
    shippingMethodText: { fontSize: 14, fontWeight: '600', color: colors.primary },
    
    footer: { backgroundColor: colors.white, padding: 16, borderTopWidth: 1, borderTopColor: colors.borderLight, ...shadow.md },
    submitBtn: { backgroundColor: colors.primary, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 14, borderRadius: 12, gap: 8 },
    submitBtnText: { color: colors.white, fontSize: 16, fontWeight: '700' },
});
